In [1]:
import numpy as np

In [5]:
a = np.array([0.3, 2.9, 4.0])

array([0.00404737, 0.0391246 , 0.05396497])

In [7]:
exp_a = np.exp(a); exp_a

array([ 1.34985881, 18.17414537, 54.59815003])

In [8]:
exp_a.sum()

74.1221542101633

In [10]:
np.exp(a)/(np.exp(a).sum())

array([0.01821127, 0.24519181, 0.73659691])

In [11]:
def softmax(X):
    return np.exp(X) / (np.exp(X).sum())

In [12]:
a = np.array([1010, 1000, 900])
softmax(a)

C:\Users\dxodn\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, nan, nan])

In [16]:
# 값이 너무 커진다.
# 최대값을 빼줘보자 어차피 식은 동일하니까
def softmax(X):
    return np.exp(X - np.max(X)) / (np.exp(X - np.max(X)).sum())

In [17]:
softmax(a)

array([9.99954602e-01, 4.53978687e-05, 1.68883521e-48])

In [19]:
print(softmax(a)[0], softmax(a)[1], softmax(a)[2])

0.9999546021312976 4.5397868702434395e-05 1.688835207224744e-48


In [20]:
softmax(a).sum()

1.0

In [23]:
def log(X):
    return np.log(X) / (np.log(X).sum())
log(a)

array([0.33535748, 0.3348751 , 0.32976742])

In [ ]:
# log를 하면 단조가 아니므